# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYIRS_9QOkJq9elysCaW2CZdzXUHq6n-

# Import the Necessary Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings('ignore')
!pip install plotly
import plotly.express as px
import plotly.graph_objects as go

"""# Load the Dataset"""

rehab = pd.read_csv('/content/Rehabs_of_Vacant_Buildings.csv')

"""# Data Overview"""

rehab2 = rehab.copy()
rehab2.head()

rehab2.info()

rehab.head()

rehab[['BLOCKLOT','Block','Lot']]

date_issues = rehab[['DateIssue','DateIssued']].sort_values(by='DateIssue')
date_issues.head()

rehab.duplicated().value_counts()

rehab.isnull().sum()

"""# Data Cleaning"""

rehab2.rename({
    'X':'Longitude',
    'Y':'Latitude',
    'OBJECTID':'Object ID'
},axis=1,inplace=True)
rehab2.head()

rehab2.drop(['DateIssued','BLOCKLOT'], inplace = True, axis = 1)
rehab2.head()

rehab2['PermitNum']= rehab2['PermitNum'].astype('string')

rehab2['PermitNum'] = rehab2['PermitNum'].str.replace(r'^USE','',regex = True)
rehab2['PermitNum'].head(20)

rehab2['PermitNum'].str.replace(r'^BUSE','', regex = True)

rehab2['PermitNum'].duplicated().value_counts()

rehab2.info()

rehab2['HousingMarketTypology2017'].value_counts()

rehab2['DateIssue'] = pd.to_datetime(rehab2['DateIssue'])
rehab2['DateIssue'].head()

rehab2[['ExistingUse','ProposedUse']].info()

rehab2['ExistingUse'] = rehab2['ExistingUse'].astype('string')
rehab2['ProposedUse'] = rehab2['ProposedUse'].astype('string')

missing = rehab2[rehab2['ExistingUse'].isnull()]
missing.info()

mv = rehab2[rehab2['ExistingUse'].isnull()]
sv = []
for idx in mv.index:
  if idx > 0:
    sv.append(idx-1)
  sv.append(idx)
  if idx < len(rehab2) - 1:
    sv.append(idx + 1)
sv = sorted(set(sv))
svdf = rehab2.loc[sv]
svdf

rehab2['ExistingUse'].isna()
rehab2.ffill(inplace=True)
rehab2.info()

string_col = rehab2.select_dtypes(include=['string']).columns
for col in string_col:
  rehab2[col] = rehab2[col].astype('object')
rehab2.info()

rehab2.head(5)

"""KPIs"""

!pip install streamlit
import streamlit as st



rehab2.head()

st.title('Vacant Buildings Dashboard')
group_col = st.selectbox('Group By:', ['Neighborhood','ExistingUse','ProposedUse','Council_District'])
breakdown = st.checkbox('Breakdown Further')
if breakdown:
  breakdown_col = st.selectbox('Breakdown By:', ['ExistingUse','ProposedUse','Council_District'])
  grouped_df = rehab2.groupby([group_col, breakdown_col]).size().reset_index(name = 'Count')
  fig = px.bar(grouped_df, x = group_col, y = 'Count', color = breakdown_col)
else:
  group_df = rehab2.groupby(group_col).size().reset_index(name = 'Count')
  fig = px.bar(group_df, x = group_col, y = 'Count')
  st.plotly_chart(fig)

!streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py

"""# Exploratory Data Analysis"""

rehab2.columns

rehab2.head()

"""##Time Based EDA"""

from pandas.core import resample
import plotly.express as px
monthly = (rehab2.dropna(subset = ['DateIssue'])
.set_index('DateIssue')
.resample('MS')
.size()
)
df_monthly = monthly.reset_index()
df_monthly.columns = ['DateIssue','Count']
fig = px.line(df_monthly, x = 'DateIssue', y = 'Count', title = 'Permits Over Time',
              labels = {'DateIssue':'Month','Count':"Count"})
fig.update_layout(width = 1200, height = 600)
fig.show()

"""##Annual Permit Count"""

annual = (rehab2.dropna(subset = 'DateIssue')
.set_index('DateIssue')
.resample('AS')
.size()
)
df_annual = annual.reset_index()
df_annual.columns = ['Year','Count']
fig = px.bar(df_annual, x = 'Year', y = 'Count')
fig.update_layout(width = 1200, height = 600)
fig.show()

"""##"""

heatmap_df = df_monthly.copy()
heatmap_df = heatmap_df.reset_index()
heatmap_df['Year'] = heatmap_df['DateIssue'].dt.year
heatmap_df['Month'] = heatmap_df['DateIssue'].dt.month

pivot = heatmap_df.pivot_table(
    index = 'Year',
    columns = 'Month',
    values = 'Count')

pivot = pivot.sort_index(axis = 1)


fig_heat = px.imshow(
    pivot,
    aspect='auto',
    color_continuous_scale='Viridis',
    labels = dict(x = 'Month', y = 'Year', color = 'Count'),
    title = 'Monthly/Annual Permit Volume'
)
fig_heat.update_layout(width = 1200, height = 600)
fig_heat.show()

"""## Geo"""

rehab2.head()

rehab2['HousingMarketTypology2017']= rehab2['HousingMarketTypology2017'].astype('string')
rehab2['HousingMarketTypology2017'].value_counts()

neighborhood_permits = (
    rehab2.groupby('Neighborhood')
    .size()
    .reset_index(name = 'Count')
    .sort_values(by = 'Count', ascending = False)
)

fig = px.bar(neighborhood_permits, x = 'Neighborhood', y = 'Count')
fig.update_layout(width = 1200, height = 600)
fig.show()

neighorhood_heatmap_df = rehab2.copy()
neighorhood_heatmap_df = neighorhood_heatmap_df.reset_index()
neighorhood_heatmap_df['Year'] = neighorhood_heatmap_df['DateIssue'].dt.year
neighorhood_heatmap_df['Count'] = neighorhood_heatmap_df.groupby('Neighborhood')['Neighborhood'].transform('count')


pivot1 = neighorhood_heatmap_df.pivot_table(
    index = 'Year',
    columns = 'Neighborhood',
    values = 'Count')

pivot1 = pivot1.sort_index(axis = 1)
fig_nhm = px.imshow(
    pivot1,
    aspect='auto',
    color_continuous_scale='Viridis',
    labels = dict(x = 'Neighborhood', y = 'Year', color = 'Count'),
    title = ''
)
fig_nhm.update_layout(width = 1200, height = 600)
fig_nhm.show()

"""## Categorical"""

existing_use_order = rehab2['ExistingUse'].value_counts().index

fig = px.histogram(rehab2, x='ExistingUse', color='ExistingUse',
                   title='Existing Use Distribution',
                   labels={'ExistingUse':'Existing Use','count':'Total'},
                   category_orders={'ExistingUse': existing_use_order}
                  )
fig.update_layout(width=1200, height=600)
fig.show()

proposed_use_order = rehab2['ProposedUse'].value_counts().index

fig = px.histogram(rehab2, x='ProposedUse', color='ProposedUse',
                   title='Proposed Use Distribution',
                   labels={'ProposedUse':'Proposed Use','count':'Total'},
                   category_orders={'ProposedUse': proposed_use_order}
                  )
fig.update_layout(width=1200, height=600)
fig.show()

"""# Data Preprocessing"""

rehab3 = rehab2.copy()

rehab3['Year'] = rehab2['DateIssue'].dt.year
rehab3['Month'] = rehab2['DateIssue'].dt.month
rehab3['Day'] = rehab2['DateIssue'].dt.day
rehab3['Time'] = rehab2['DateIssue'].dt.time
rehab3.drop('DateIssue', inplace = True, axis = 1)
rehab3.head()

drop_cols = ['Object ID','Block','VBN','Lot','PermitNum','Time','Address','Neighborhood','Day','Council_District']

X = rehab3.drop(columns = drop_cols, errors = 'ignore')
rehab3.shape, X.shape

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

num_features = ['Year','Month']
cat_features = ['ExistingUse','ProposedUse']
geo_features = ['Longitude','Latitude']

num_pipeline = Pipeline(steps = [
    #('imputer', SimpleImputer(strategy = 'median')),
    ('scaler', StandardScaler())
])

cat_pipeline = Pipeline(steps = [
   # ('imputer', SimpleImputer(strategy = 'most_frequent'))
('onehot', OneHotEncoder(handle_unknown = 'ignore'))
])

geo_pipeline = Pipeline(steps = [
    ('scaler', StandardScaler())
])
preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_pipeline, num_features),
        ('cat', cat_pipeline, cat_features),
        ('geo', geo_pipeline, geo_features)
    ],
    remainder='drop'
)

num_features

X_proc = preprocessor.fit_transform(X)

def elbow_silhouette(
    X_proc,
    k_min=2,
    k_max=12,
    random_state=42):
  ks = list(range(k_min, k_max + 1))
  inertias, silhouettes = [], []


  for k in ks:
      km = KMeans(n_clusters=k, random_state=random_state, n_init="auto")
      labels = km.fit_predict(X_proc)
      inertias.append(km.inertia_)
      silhouettes.append(silhouette_score(X_proc, labels, sample_size = 5000, random_state=random_state))

      return ks, inertias, silhouettes

ks, inertias, silhouettes = elbow_silhouette(
    X_proc,
    k_min=2,
    k_max=12,
    random_state=42

)

best_k = ks[int(np.argmax(silhouettes))]
print(f"Best k by silhouette: {best_k} (score={max(silhouettes):.4f})")

X.columns.tolist()

num_features, cat_features, geo_features

rehab3.dtypes

import geopandas as gpd
gdf = gpd.GeoDataFrame(rehab3)
gdf.set_geometry(gpd.points_from_xy(gdf.Longitude, gdf.Latitude), inplace=True)
gdf

# To fix the 'NoneType' error due to a previous incorrect assignment to 'gdf',
# we explicitly re-create the GeoDataFrame 'gdf' using the 'rehab3' DataFrame.
# Ideally, the cell where 'gdf' was originally defined (EthBm8pOQLTz) should be re-run,
# but this ensures the current cell executes correctly.
gdf = gpd.GeoDataFrame(rehab3)
gdf.set_geometry(gpd.points_from_xy(gdf.Longitude, gdf.Latitude), inplace=True)

gdf.to_file("gdf.shp")
gdf.head()

rehab2['Transitions'] = rehab2['ExistingUse'] + '->' + rehab2['ProposedUse']
rehab2['Transitions'].value_counts().head(15)

rehab2['MonthYear'] = pd.to_datetime(rehab2['DateIssue']).dt.to_period('M')
trend = rehab2.groupby('MonthYear').size().reset_index(name='Count') # Convert the Series to a DataFrame with 'Count' column
trend['MonthYear'] = trend['MonthYear'].dt.to_timestamp() # Convert Period objects to Timestamp objects
px.line(trend, # Pass the DataFrame created from trend
        x = 'MonthYear', # Specify the column name for the x-axis
        y = 'Count', # Specify the column name for the y-axis
        title = 'Permits Over Time')

px.bar(rehab2['Council_District'].value_counts().reset_index(),
       color = 'Council_District',
       color_continuous_scale = 'Viridis')

import geopandas as gpd
from shapely.geometry import Point

gdf = gpd.GeoDataFrame(
    rehab2, # Pass the original DataFrame here
    geometry = [Point(xy) for xy in zip(rehab2['Longitude'], rehab2['Latitude'])],
    crs = 'EPSG:2248'
)
gdf = gdf.to_crs(epsg = 4326)
gdf['Latitude'] = gdf['geometry'].y
gdf['Longitude'] = gdf['geometry'].x

color_map = {
    'A':'lightpink',
    'B': 'pink',
    'C': 'red',
    'D': 'darkorange',
    'E':'orange',
    'F': 'yellow',
    'G':'yellowgreen',
    'H':'green',
    'I':'lightblue',
    'J':'blue',
    'Rental Market 1':'darkblue',
    'Subsidized Rental Market':'lavender',
    "NonResidential":'purple',
    'Mixed Market/Subsd Rental':'grey'}

fig = px.scatter_mapbox(gdf,
      lat = 'Latitude',
      lon = 'Longitude',
      opacity = 0.5,
      zoom = 10,
      color = 'HousingMarketTypology2017',
      color_discrete_map = color_map, # Added color to visualize different typologies
      color_continuous_scale='Viridis',
      hover_data={'HousingMarketTypology2017':True,'Latitude':':.1f','Longitude':':.1f','Neighborhood':True},
      )
fig.update_layout(mapbox_style = 'carto-darkmatter',
                height = 800)
fig.show()